### ISSUE TITLE
How to Have a GUI using the .dll File

### ISSUE THREAD

**Issue by Applejr2357** [Omega172/Blush-Blush-Cheat#1]
Hi! I was wondering how you were able to have an interface with the .dll file. I was able to inject the .dll into the game, but the first image I wasn't able to recreate. I was wondering how you did that. (Sorry, I'm not very good with computers.)

**Comment by Omega172** [comment]
Make sure you have installed the dependencies:

Microsoft Visual C++ Redistributable x86 - https://aka.ms/vs/17/release/vc_redist.x86.exe
Microsoft Visual C++ Redistributable x64 - https://aka.ms/vs/17/release/vc_redist.x64.exe
DirectX End-User Runtimes (June 2010) - http://www.microsoft.com/en-us/download/confirmation.aspx?id=8109

After you have installed them restart your pc.

**Comment by Applejr2357** [comment]
Hi! Thank you very much for your reply!
I reinstalled all three of the dependencies and restarted my PC, but I am still unable to get the interface to appear. It seems to still be the same where I have the command prompt window and everything seems to match the second image (the one I attached), but I can't seem to get the first image with the GUI. Is there something I need to click on inside the game after I've injected the .dll? 
I'm very sorry to inconvenience you. Thank you for your help!
![image](https://github.com/Omega172/Blush-Blush-Cheat/assets/146039719/e3a78fad-f769-49e3-a5db-db9c3688eab8)

**Comment by Omega172** [comment]
Do you see the fps display in the top left corner?

If so then the menu rendering is working and you need to press the "Insert" key on your keyboard it is usually near delete and backspace

if you do not have an "Insert" key you can change it in main.cpp line 52
using any of these keycodes https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes

Sorry for taking so long to respond.

**Comment by Applejr2357** [comment]
Don't worry, thanks for responding at all, I know you aren't obligated to play tech support on old projects so I'm very appreciative of your help. I now see that you said that you had to press Insert to show the GUI and I feel silly that I didn't notice that earlier. It's working fine now. Thanks again!
