### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by firetruck000** [Omega172/Blush-Blush-Cheat#2]
Hello, thanks for the hack but how can I install this?

**Comment by Omega172** [comment]
1. Download and install the dependencies listed in the README, restart PC after installing dependencies.
2. Either compile the DLL or download the compiled one from [Releases](https://github.com/Omega172/Blush-Blush-Cheat/releases/latest).
3. Using a DLL injector of your choice Inject the DLL into BlushBlush.exe.

For a DLL injector, if you are very new to this I recommend [Process Hacker](https://processhacker.sourceforge.io/)

[How to inject DLL with Process Hacker](https://www.unknowncheats.me/forum/general-programming-and-reversing/378956-process-hacker-2-inject-dll-game.html)
